USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION
    BANKING_S3_INTEGRATION
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN =
    'arn:aws:iam::981207388521:role/snowflake-banking-s3-role'
STORAGE_ALLOWED_LOCATIONS = (
    's3://enterprise-banking-etl-raw/raw/'
);

DESC INTEGRATION BANKING_S3_INTEGRATION;

GRANT USAGE ON INTEGRATION BANKING_S3_INTEGRATION TO ROLE SYSADMIN;