USE ROLE SYSADMIN;

USE DATABASE ENTERPRISE_BANKING;

USE SCHEMA RAW;

CREATE OR REPLACE STAGE
    BANKING_RAW_STAGE
URL = 's3://enterprise-banking-etl-raw/raw/'
STORAGE_INTEGRATION =
    BANKING_S3_INTEGRATION
FILE_FORMAT =
    PARQUET_FILE_FORMAT;

LIST @BANKING_RAW_STAGE;