USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS
    ENTERPRISE_BANKING;

USE DATABASE ENTERPRISE_BANKING;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE SCHEMA IF NOT EXISTS STAGING;

CREATE SCHEMA IF NOT EXISTS CORE;

CREATE SCHEMA IF NOT EXISTS MARTS;