USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS FACT_TRANSACTIONS
(
    TRANSACTION_ID VARCHAR NOT NULL,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    BRANCH_ID VARCHAR,

    TRANSACTION_TYPE VARCHAR,
    TRANSACTION_DIRECTION VARCHAR,

    TRANSACTION_AMOUNT NUMBER(18, 2),
    TRANSACTION_STATUS VARCHAR,

    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    TRANSACTION_DATE DATE,

    TRANSACTION_CHANNEL VARCHAR,

    MERCHANT_NAME VARCHAR,
    MERCHANT_CATEGORY VARCHAR,

    TRANSACTION_CITY VARCHAR,
    TRANSACTION_STATE VARCHAR,

    CURRENCY_CODE VARCHAR,
    BATCH_ID VARCHAR,

    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,

    RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ,

    CREATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    UPDATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_TRANSACTIONS
        PRIMARY KEY (TRANSACTION_ID)
);