USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS FACT_FRAUD
(
    FRAUD_CASE_ID VARCHAR NOT NULL,

    TRANSACTION_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    BRANCH_ID VARCHAR,

    FRAUD_TYPE VARCHAR,

    RISK_SCORE NUMBER,
    RISK_LEVEL VARCHAR,
    CASE_STATUS VARCHAR,

    TRANSACTION_AMOUNT NUMBER(18, 2),
    TRANSACTION_TYPE VARCHAR,
    TRANSACTION_CHANNEL VARCHAR,

    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,

    MERCHANT_NAME VARCHAR,
    MERCHANT_CATEGORY VARCHAR,

    DETECTED_TIMESTAMP TIMESTAMP_NTZ,
    DETECTED_DATE DATE,

    BATCH_ID VARCHAR,

    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,

    RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ,

    CREATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    UPDATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_FRAUD
        PRIMARY KEY (FRAUD_CASE_ID)
);