USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA RAW;

CREATE STREAM IF NOT EXISTS STR_RAW_TRANSACTIONS
ON TABLE RAW_TRANSACTIONS
APPEND_ONLY = TRUE;

CREATE STREAM IF NOT EXISTS STR_RAW_FRAUD
ON TABLE RAW_FRAUD
APPEND_ONLY = TRUE;