USE DATABASE ENTERPRISE_BANKING;
INSERT INTO CORE.FACT_TRANSACTIONS
(
    TRANSACTION_ID,
    ACCOUNT_ID,
    CUSTOMER_ID,
    BRANCH_ID,
    TRANSACTION_TYPE,
    TRANSACTION_DIRECTION,
    TRANSACTION_AMOUNT,
    TRANSACTION_STATUS,
    TRANSACTION_TIMESTAMP,
    TRANSACTION_DATE,
    TRANSACTION_CHANNEL,
    MERCHANT_NAME,
    MERCHANT_CATEGORY,
    TRANSACTION_CITY,
    TRANSACTION_STATE,
    CURRENCY_CODE,
    BATCH_ID,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER,
    RAW_LOAD_TIMESTAMP
)

SELECT
    TRANSACTION_ID,
    ACCOUNT_ID,
    CUSTOMER_ID,
    BRANCH_ID,
    TRANSACTION_TYPE,
    TRANSACTION_DIRECTION,
    TRANSACTION_AMOUNT,
    TRANSACTION_STATUS,
    TRANSACTION_TIMESTAMP,
    TRANSACTION_TIMESTAMP::DATE,
    TRANSACTION_CHANNEL,
    MERCHANT_NAME,
    MERCHANT_CATEGORY,
    TRANSACTION_CITY,
    TRANSACTION_STATE,
    CURRENCY_CODE,
    BATCH_ID,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER,
    LOAD_TIMESTAMP

FROM STAGING.STG_TRANSACTIONS;