USE DATABASE ENTERPRISE_BANKING;
INSERT INTO CORE.FACT_FRAUD
(
    FRAUD_CASE_ID,
    TRANSACTION_ID,
    ACCOUNT_ID,
    CUSTOMER_ID,
    BRANCH_ID,
    FRAUD_TYPE,
    RISK_SCORE,
    RISK_LEVEL,
    CASE_STATUS,
    TRANSACTION_AMOUNT,
    TRANSACTION_TYPE,
    TRANSACTION_CHANNEL,
    TRANSACTION_TIMESTAMP,
    MERCHANT_NAME,
    MERCHANT_CATEGORY,
    DETECTED_TIMESTAMP,
    DETECTED_DATE,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER,
    RAW_LOAD_TIMESTAMP
)

SELECT
    FRAUD_CASE_ID,
    TRANSACTION_ID,
    ACCOUNT_ID,
    CUSTOMER_ID,
    BRANCH_ID,
    FRAUD_TYPE,
    RISK_SCORE,
    RISK_LEVEL,
    CASE_STATUS,
    TRANSACTION_AMOUNT,
    TRANSACTION_TYPE,
    TRANSACTION_CHANNEL,
    TRANSACTION_TIMESTAMP,
    MERCHANT_NAME,
    MERCHANT_CATEGORY,
    DETECTED_TIMESTAMP,
    DETECTED_TIMESTAMP::DATE,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER,
    LOAD_TIMESTAMP

FROM STAGING.STG_FRAUD;