USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

MERGE INTO FACT_TRANSACTIONS AS TARGET

USING
(
    SELECT
        RAW_RECORD:transaction_id::VARCHAR
            AS TRANSACTION_ID,

        RAW_RECORD:account_id::VARCHAR
            AS ACCOUNT_ID,

        RAW_RECORD:customer_id::VARCHAR
            AS CUSTOMER_ID,

        RAW_RECORD:branch_id::VARCHAR
            AS BRANCH_ID,

        RAW_RECORD:transaction_type::VARCHAR
            AS TRANSACTION_TYPE,

        RAW_RECORD:transaction_direction::VARCHAR
            AS TRANSACTION_DIRECTION,

        RAW_RECORD:transaction_amount::NUMBER(18, 2)
            AS TRANSACTION_AMOUNT,

        RAW_RECORD:transaction_status::VARCHAR
            AS TRANSACTION_STATUS,

        TRY_TO_TIMESTAMP_NTZ(
            RAW_RECORD:transaction_timestamp::VARCHAR
        ) AS TRANSACTION_TIMESTAMP,

        TRY_TO_TIMESTAMP_NTZ(
            RAW_RECORD:transaction_timestamp::VARCHAR
        )::DATE AS TRANSACTION_DATE,

        RAW_RECORD:transaction_channel::VARCHAR
            AS TRANSACTION_CHANNEL,

        RAW_RECORD:merchant_name::VARCHAR
            AS MERCHANT_NAME,

        RAW_RECORD:merchant_category::VARCHAR
            AS MERCHANT_CATEGORY,

        RAW_RECORD:transaction_city::VARCHAR
            AS TRANSACTION_CITY,

        RAW_RECORD:transaction_state::VARCHAR
            AS TRANSACTION_STATE,

        RAW_RECORD:currency_code::VARCHAR
            AS CURRENCY_CODE,

        RAW_RECORD:batch_id::VARCHAR
            AS BATCH_ID,

        SOURCE_FILE,

        SOURCE_ROW_NUMBER,

        LOAD_TIMESTAMP
            AS RAW_LOAD_TIMESTAMP

    FROM RAW.STR_RAW_TRANSACTIONS

    WHERE METADATA$ACTION = 'INSERT'

    QUALIFY ROW_NUMBER() OVER
    (
        PARTITION BY
            RAW_RECORD:transaction_id::VARCHAR

        ORDER BY
            LOAD_TIMESTAMP DESC,
            SOURCE_ROW_NUMBER DESC
    ) = 1
)
AS SOURCE

ON
    TARGET.TRANSACTION_ID
    = SOURCE.TRANSACTION_ID

WHEN MATCHED THEN UPDATE SET

    TARGET.ACCOUNT_ID =
        SOURCE.ACCOUNT_ID,

    TARGET.CUSTOMER_ID =
        SOURCE.CUSTOMER_ID,

    TARGET.BRANCH_ID =
        SOURCE.BRANCH_ID,

    TARGET.TRANSACTION_TYPE =
        SOURCE.TRANSACTION_TYPE,

    TARGET.TRANSACTION_DIRECTION =
        SOURCE.TRANSACTION_DIRECTION,

    TARGET.TRANSACTION_AMOUNT =
        SOURCE.TRANSACTION_AMOUNT,

    TARGET.TRANSACTION_STATUS =
        SOURCE.TRANSACTION_STATUS,

    TARGET.TRANSACTION_TIMESTAMP =
        SOURCE.TRANSACTION_TIMESTAMP,

    TARGET.TRANSACTION_DATE =
        SOURCE.TRANSACTION_DATE,

    TARGET.TRANSACTION_CHANNEL =
        SOURCE.TRANSACTION_CHANNEL,

    TARGET.MERCHANT_NAME =
        SOURCE.MERCHANT_NAME,

    TARGET.MERCHANT_CATEGORY =
        SOURCE.MERCHANT_CATEGORY,

    TARGET.TRANSACTION_CITY =
        SOURCE.TRANSACTION_CITY,

    TARGET.TRANSACTION_STATE =
        SOURCE.TRANSACTION_STATE,

    TARGET.CURRENCY_CODE =
        SOURCE.CURRENCY_CODE,

    TARGET.BATCH_ID =
        SOURCE.BATCH_ID,

    TARGET.SOURCE_FILE =
        SOURCE.SOURCE_FILE,

    TARGET.SOURCE_ROW_NUMBER =
        SOURCE.SOURCE_ROW_NUMBER,

    TARGET.RAW_LOAD_TIMESTAMP =
        SOURCE.RAW_LOAD_TIMESTAMP,

    TARGET.UPDATED_TIMESTAMP =
        CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    TRANSACTION_ID,
    ACCOUNT_ID,
    CUSTOMER_ID,
    BRANCH_ID,
    TRANSACTION_TYPE,
    TRANSACTION_DIRECTION,
    TRANSACTION_AMOUNT,
    TRANSACTION_STATUS,
    TRANSACTION_TIMESTAMP,
    TRANSACTION_DATE,
    TRANSACTION_CHANNEL,
    MERCHANT_NAME,
    MERCHANT_CATEGORY,
    TRANSACTION_CITY,
    TRANSACTION_STATE,
    CURRENCY_CODE,
    BATCH_ID,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER,
    RAW_LOAD_TIMESTAMP
)

VALUES
(
    SOURCE.TRANSACTION_ID,
    SOURCE.ACCOUNT_ID,
    SOURCE.CUSTOMER_ID,
    SOURCE.BRANCH_ID,
    SOURCE.TRANSACTION_TYPE,
    SOURCE.TRANSACTION_DIRECTION,
    SOURCE.TRANSACTION_AMOUNT,
    SOURCE.TRANSACTION_STATUS,
    SOURCE.TRANSACTION_TIMESTAMP,
    SOURCE.TRANSACTION_DATE,
    SOURCE.TRANSACTION_CHANNEL,
    SOURCE.MERCHANT_NAME,
    SOURCE.MERCHANT_CATEGORY,
    SOURCE.TRANSACTION_CITY,
    SOURCE.TRANSACTION_STATE,
    SOURCE.CURRENCY_CODE,
    SOURCE.BATCH_ID,
    SOURCE.SOURCE_FILE,
    SOURCE.SOURCE_ROW_NUMBER,
    SOURCE.RAW_LOAD_TIMESTAMP
);