USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

MERGE INTO FACT_FRAUD AS TARGET

USING
(
    SELECT
        RAW_RECORD:fraud_case_id::VARCHAR
            AS FRAUD_CASE_ID,

        RAW_RECORD:transaction_id::VARCHAR
            AS TRANSACTION_ID,

        RAW_RECORD:account_id::VARCHAR
            AS ACCOUNT_ID,

        RAW_RECORD:customer_id::VARCHAR
            AS CUSTOMER_ID,

        RAW_RECORD:branch_id::VARCHAR
            AS BRANCH_ID,

        RAW_RECORD:fraud_type::VARCHAR
            AS FRAUD_TYPE,

        RAW_RECORD:risk_score::NUMBER
            AS RISK_SCORE,

        RAW_RECORD:risk_level::VARCHAR
            AS RISK_LEVEL,

        RAW_RECORD:case_status::VARCHAR
            AS CASE_STATUS,

        RAW_RECORD:transaction_amount::NUMBER(18, 2)
            AS TRANSACTION_AMOUNT,

        RAW_RECORD:transaction_type::VARCHAR
            AS TRANSACTION_TYPE,

        RAW_RECORD:transaction_channel::VARCHAR
            AS TRANSACTION_CHANNEL,

        TRY_TO_TIMESTAMP_NTZ(
            RAW_RECORD:transaction_timestamp::VARCHAR
        ) AS TRANSACTION_TIMESTAMP,

        RAW_RECORD:merchant_name::VARCHAR
            AS MERCHANT_NAME,

        RAW_RECORD:merchant_category::VARCHAR
            AS MERCHANT_CATEGORY,

        TRY_TO_TIMESTAMP_NTZ(
            RAW_RECORD:detected_timestamp::VARCHAR
        ) AS DETECTED_TIMESTAMP,

        TRY_TO_TIMESTAMP_NTZ(
            RAW_RECORD:detected_timestamp::VARCHAR
        )::DATE AS DETECTED_DATE,

        RAW_RECORD:batch_id::VARCHAR
            AS BATCH_ID,

        SOURCE_FILE,

        SOURCE_ROW_NUMBER,

        LOAD_TIMESTAMP
            AS RAW_LOAD_TIMESTAMP

    FROM RAW.STR_RAW_FRAUD

    WHERE METADATA$ACTION = 'INSERT'

    QUALIFY ROW_NUMBER() OVER
    (
        PARTITION BY
            RAW_RECORD:fraud_case_id::VARCHAR

        ORDER BY
            LOAD_TIMESTAMP DESC,
            SOURCE_ROW_NUMBER DESC
    ) = 1
)
AS SOURCE

ON
    TARGET.FRAUD_CASE_ID
    = SOURCE.FRAUD_CASE_ID

WHEN MATCHED THEN UPDATE SET

    TARGET.CASE_STATUS =
        SOURCE.CASE_STATUS,

    TARGET.RISK_SCORE =
        SOURCE.RISK_SCORE,

    TARGET.RISK_LEVEL =
        SOURCE.RISK_LEVEL,

    TARGET.SOURCE_FILE =
        SOURCE.SOURCE_FILE,

    TARGET.SOURCE_ROW_NUMBER =
        SOURCE.SOURCE_ROW_NUMBER,

    TARGET.RAW_LOAD_TIMESTAMP =
        SOURCE.RAW_LOAD_TIMESTAMP,

    TARGET.UPDATED_TIMESTAMP =
        CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
    FRAUD_CASE_ID,
    TRANSACTION_ID,
    ACCOUNT_ID,
    CUSTOMER_ID,
    BRANCH_ID,
    FRAUD_TYPE,
    RISK_SCORE,
    RISK_LEVEL,
    CASE_STATUS,
    TRANSACTION_AMOUNT,
    TRANSACTION_TYPE,
    TRANSACTION_CHANNEL,
    TRANSACTION_TIMESTAMP,
    MERCHANT_NAME,
    MERCHANT_CATEGORY,
    DETECTED_TIMESTAMP,
    DETECTED_DATE,
    BATCH_ID,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER,
    RAW_LOAD_TIMESTAMP
)

VALUES
(
    SOURCE.FRAUD_CASE_ID,
    SOURCE.TRANSACTION_ID,
    SOURCE.ACCOUNT_ID,
    SOURCE.CUSTOMER_ID,
    SOURCE.BRANCH_ID,
    SOURCE.FRAUD_TYPE,
    SOURCE.RISK_SCORE,
    SOURCE.RISK_LEVEL,
    SOURCE.CASE_STATUS,
    SOURCE.TRANSACTION_AMOUNT,
    SOURCE.TRANSACTION_TYPE,
    SOURCE.TRANSACTION_CHANNEL,
    SOURCE.TRANSACTION_TIMESTAMP,
    SOURCE.MERCHANT_NAME,
    SOURCE.MERCHANT_CATEGORY,
    SOURCE.DETECTED_TIMESTAMP,
    SOURCE.DETECTED_DATE,
    SOURCE.BATCH_ID,
    SOURCE.SOURCE_FILE,
    SOURCE.SOURCE_ROW_NUMBER,
    SOURCE.RAW_LOAD_TIMESTAMP
);