SELECT
    'FACT_TRANSACTIONS' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT TRANSACTION_ID)
        AS DISTINCT_KEY_COUNT
FROM CORE.FACT_TRANSACTIONS

UNION ALL

SELECT
    'FACT_FRAUD',
    COUNT(*),
    COUNT(DISTINCT FRAUD_CASE_ID)
FROM CORE.FACT_FRAUD;