USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS PIPELINE_AUDIT
(
    AUDIT_ID NUMBER AUTOINCREMENT,

    PIPELINE_NAME VARCHAR NOT NULL,
    BATCH_ID VARCHAR,
    EXECUTION_DATE DATE,

    TRANSACTION_COUNT NUMBER,
    FRAUD_COUNT NUMBER,

    PIPELINE_STATUS VARCHAR,

    START_TIMESTAMP TIMESTAMP_NTZ,
    END_TIMESTAMP TIMESTAMP_NTZ,

    CREATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_PIPELINE_AUDIT
        PRIMARY KEY (AUDIT_ID)
);