USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

SELECT
    COUNT(*) > 0
    AND COUNT_IF(
        TRANSACTION_ID IS NULL
    ) = 0
    AND COUNT_IF(
        TRANSACTION_AMOUNT <= 0
    ) = 0
    AND COUNT_IF(
        TRANSACTION_TIMESTAMP IS NULL
    ) = 0
    AND (
        COUNT(*)
        =
        COUNT(DISTINCT TRANSACTION_ID)
    )
FROM FACT_TRANSACTIONS
WHERE TRANSACTION_DATE = '{{ ds }}';