USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

MERGE INTO PIPELINE_AUDIT AS TARGET

USING
(
    SELECT
        'BANKING_DAILY_INCREMENTAL'
            AS PIPELINE_NAME,

        'DAILY_{{ ds_nodash }}'
            AS BATCH_ID,

        '{{ ds }}'::DATE
            AS EXECUTION_DATE,

        (
            SELECT COUNT(*)
            FROM FACT_TRANSACTIONS
            WHERE TRANSACTION_DATE =
                '{{ ds }}'::DATE
        ) AS TRANSACTION_COUNT,

        (
            SELECT COUNT(*)
            FROM FACT_FRAUD
            WHERE DETECTED_DATE =
                '{{ ds }}'::DATE
        ) AS FRAUD_COUNT,

        'SUCCESS'
            AS PIPELINE_STATUS,

        CURRENT_TIMESTAMP()
            AS END_TIMESTAMP
)
AS SOURCE

ON
    TARGET.PIPELINE_NAME =
        SOURCE.PIPELINE_NAME

AND TARGET.EXECUTION_DATE =
        SOURCE.EXECUTION_DATE

WHEN MATCHED THEN UPDATE SET

    TARGET.BATCH_ID =
        SOURCE.BATCH_ID,

    TARGET.TRANSACTION_COUNT =
        SOURCE.TRANSACTION_COUNT,

    TARGET.FRAUD_COUNT =
        SOURCE.FRAUD_COUNT,

    TARGET.PIPELINE_STATUS =
        SOURCE.PIPELINE_STATUS,

    TARGET.END_TIMESTAMP =
        SOURCE.END_TIMESTAMP

WHEN NOT MATCHED THEN INSERT
(
    PIPELINE_NAME,
    BATCH_ID,
    EXECUTION_DATE,
    TRANSACTION_COUNT,
    FRAUD_COUNT,
    PIPELINE_STATUS,
    START_TIMESTAMP,
    END_TIMESTAMP
)

VALUES
(
    SOURCE.PIPELINE_NAME,
    SOURCE.BATCH_ID,
    SOURCE.EXECUTION_DATE,
    SOURCE.TRANSACTION_COUNT,
    SOURCE.FRAUD_COUNT,
    SOURCE.PIPELINE_STATUS,
    CURRENT_TIMESTAMP(),
    SOURCE.END_TIMESTAMP
);