USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,

    CUSTOMER_ID VARCHAR NOT NULL,
    BRANCH_ID VARCHAR,

    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,

    DATE_OF_BIRTH DATE,
    GENDER VARCHAR,

    EMAIL VARCHAR,
    PHONE_NUMBER VARCHAR,

    CITY VARCHAR,
    STATE VARCHAR,
    ZIP_CODE VARCHAR,

    CUSTOMER_PROFILE VARCHAR,
    CUSTOMER_STATUS VARCHAR,

    ANNUAL_INCOME NUMBER(18, 2),
    CREDIT_SCORE NUMBER,

    CUSTOMER_SINCE DATE,

    EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL,
    EFFECTIVE_TO TIMESTAMP_NTZ,

    IS_CURRENT BOOLEAN NOT NULL,

    RECORD_HASH VARCHAR,

    SOURCE_FILE VARCHAR,
    RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ,

    CREATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    UPDATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_DIM_CUSTOMER
        PRIMARY KEY (CUSTOMER_KEY)
);