USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

SELECT
    COUNT(*) > 0

    AND COUNT_IF(
        CUSTOMER_ID IS NULL
    ) = 0

    AND COUNT_IF(
        IS_CURRENT = TRUE
        AND EFFECTIVE_TO IS NOT NULL
    ) = 0

    AND COUNT_IF(
        IS_CURRENT = FALSE
        AND EFFECTIVE_TO IS NULL
    ) = 0

    AND NOT EXISTS
    (
        SELECT 1
        FROM DIM_CUSTOMER
        WHERE IS_CURRENT = TRUE
        GROUP BY CUSTOMER_ID
        HAVING COUNT(*) > 1
    )

FROM DIM_CUSTOMER;