USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE OR REPLACE TABLE CORE.DIM_BRANCH
(
    BRANCH_KEY NUMBER AUTOINCREMENT,

    BRANCH_ID VARCHAR,
    BRANCH_CODE VARCHAR,
    BRANCH_NAME VARCHAR,
    BRANCH_TYPE VARCHAR,

    CITY VARCHAR,
    STATE VARCHAR,
    ZIP_CODE VARCHAR,
    COUNTRY VARCHAR,

    PHONE_NUMBER VARCHAR,

    BRANCH_STATUS VARCHAR,
    OPEN_DATE DATE,

    SOURCE_FILE VARCHAR,
    RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ,

    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (BRANCH_KEY)
);