USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

MERGE INTO DIM_BRANCH AS TARGET

USING
(
    SELECT
        BRANCH_ID,
        BRANCH_CODE,
        BRANCH_NAME,
        BRANCH_TYPE,
        CITY,
        STATE,
        ZIP_CODE,
        COUNTRY,
        PHONE_NUMBER,
        BRANCH_STATUS,
        OPENED_DATE,
        SOURCE_FILE,
        LOAD_TIMESTAMP AS RAW_LOAD_TIMESTAMP

    FROM STAGING.STG_BRANCHES

    QUALIFY ROW_NUMBER() OVER
    (
        PARTITION BY BRANCH_ID
        ORDER BY LOAD_TIMESTAMP DESC
    ) = 1
) SOURCE

ON TARGET.BRANCH_ID = SOURCE.BRANCH_ID

WHEN MATCHED THEN
UPDATE SET

    TARGET.BRANCH_CODE = SOURCE.BRANCH_CODE,
    TARGET.BRANCH_NAME = SOURCE.BRANCH_NAME,
    TARGET.BRANCH_TYPE = SOURCE.BRANCH_TYPE,
    TARGET.CITY = SOURCE.CITY,
    TARGET.STATE = SOURCE.STATE,
    TARGET.ZIP_CODE = SOURCE.ZIP_CODE,
    TARGET.COUNTRY = SOURCE.COUNTRY,
    TARGET.PHONE_NUMBER = SOURCE.PHONE_NUMBER,
    TARGET.BRANCH_STATUS = SOURCE.BRANCH_STATUS,
    TARGET.OPEN_DATE = SOURCE.OPENED_DATE,
    TARGET.SOURCE_FILE = SOURCE.SOURCE_FILE,
    TARGET.RAW_LOAD_TIMESTAMP = SOURCE.RAW_LOAD_TIMESTAMP,
    TARGET.UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN
INSERT
(
    BRANCH_ID,
    BRANCH_CODE,
    BRANCH_NAME,
    BRANCH_TYPE,
    CITY,
    STATE,
    ZIP_CODE,
    COUNTRY,
    PHONE_NUMBER,
    BRANCH_STATUS,
    OPEN_DATE,
    SOURCE_FILE,
    RAW_LOAD_TIMESTAMP
)

VALUES
(
    SOURCE.BRANCH_ID,
    SOURCE.BRANCH_CODE,
    SOURCE.BRANCH_NAME,
    SOURCE.BRANCH_TYPE,
    SOURCE.CITY,
    SOURCE.STATE,
    SOURCE.ZIP_CODE,
    SOURCE.COUNTRY,
    SOURCE.PHONE_NUMBER,
    SOURCE.BRANCH_STATUS,
    SOURCE.OPENED_DATE,
    SOURCE.SOURCE_FILE,
    SOURCE.RAW_LOAD_TIMESTAMP
);