USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS DIM_ACCOUNT
(
    ACCOUNT_KEY NUMBER IDENTITY(1,1),

    ACCOUNT_ID VARCHAR NOT NULL,
    ACCOUNT_NUMBER VARCHAR,

    CUSTOMER_ID VARCHAR,

    BRANCH_ID VARCHAR,
    BRANCH_CODE VARCHAR,

    ACCOUNT_TYPE VARCHAR,
    ACCOUNT_STATUS VARCHAR,

    CURRENCY_CODE VARCHAR,

    CURRENT_BALANCE NUMBER(18,2),
    AVAILABLE_BALANCE NUMBER(18,2),

    INTEREST_RATE NUMBER(10,6),

    OPENED_DATE DATE,
    CLOSED_DATE DATE,

    EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL,
    EFFECTIVE_TO TIMESTAMP_NTZ,

    IS_CURRENT BOOLEAN NOT NULL,

    RECORD_HASH VARCHAR(64),

    SOURCE_FILE VARCHAR,
    RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ,

    CREATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    UPDATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_DIM_ACCOUNT
        PRIMARY KEY (ACCOUNT_KEY)
);