USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

INSERT INTO DIM_ACCOUNT
(
    ACCOUNT_ID,
    ACCOUNT_NUMBER,
    CUSTOMER_ID,
    BRANCH_ID,
    BRANCH_CODE,
    ACCOUNT_TYPE,
    ACCOUNT_STATUS,
    CURRENCY_CODE,
    CURRENT_BALANCE,
    AVAILABLE_BALANCE,
    INTEREST_RATE,
    OPENED_DATE,
    CLOSED_DATE,

    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT,

    RECORD_HASH,

    SOURCE_FILE,
    RAW_LOAD_TIMESTAMP
)

SELECT

    ACCOUNT_ID,
    ACCOUNT_NUMBER,
    CUSTOMER_ID,
    BRANCH_ID,
    BRANCH_CODE,
    ACCOUNT_TYPE,
    ACCOUNT_STATUS,
    CURRENCY_CODE,
    CURRENT_BALANCE,
    AVAILABLE_BALANCE,
    INTEREST_RATE,
    OPENED_DATE,
    CLOSED_DATE,

    LOAD_TIMESTAMP,
    NULL,
    TRUE,

    SHA2(
        CONCAT_WS(
            '|',

            COALESCE(CUSTOMER_ID,''),

            COALESCE(BRANCH_ID,''),

            COALESCE(BRANCH_CODE,''),

            COALESCE(ACCOUNT_TYPE,''),

            COALESCE(ACCOUNT_STATUS,''),

            COALESCE(CURRENCY_CODE,''),

            COALESCE(
                INTEREST_RATE::VARCHAR,
                ''
            ),

            COALESCE(
                CLOSED_DATE::VARCHAR,
                ''
            )
        ),
        256
    ),

    SOURCE_FILE,

    LOAD_TIMESTAMP

FROM STAGING.STG_ACCOUNTS

QUALIFY ROW_NUMBER() OVER
(
    PARTITION BY ACCOUNT_ID
    ORDER BY LOAD_TIMESTAMP DESC
)=1;