USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS DIM_DATE
(
    DATE_KEY NUMBER(8) PRIMARY KEY,

    FULL_DATE DATE NOT NULL,

    YEAR NUMBER(4),
    QUARTER NUMBER(1),

    MONTH NUMBER(2),
    MONTH_NAME VARCHAR(20),
    MONTH_SHORT VARCHAR(3),

    WEEK_OF_YEAR NUMBER(2),

    DAY_OF_MONTH NUMBER(2),
    DAY_OF_WEEK NUMBER(1),
    DAY_NAME VARCHAR(15),

    DAY_OF_YEAR NUMBER(3),

    IS_WEEKEND BOOLEAN,

    IS_MONTH_START BOOLEAN,
    IS_MONTH_END BOOLEAN,

    IS_QUARTER_START BOOLEAN,
    IS_QUARTER_END BOOLEAN,

    IS_YEAR_START BOOLEAN,
    IS_YEAR_END BOOLEAN,

    FISCAL_YEAR NUMBER(4),

    CREATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP()
);