USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

SELECT

    COUNT(*)                       AS TOTAL_DAYS,

    MIN(FULL_DATE)                 AS START_DATE,

    MAX(FULL_DATE)                 AS END_DATE,

    COUNT(DISTINCT DATE_KEY)       AS DISTINCT_KEYS

FROM DIM_DATE;