USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS DIM_MERCHANT
(
    MERCHANT_KEY NUMBER IDENTITY(1,1),

    MERCHANT_ID VARCHAR(64) NOT NULL,

    MERCHANT_NAME VARCHAR,
    MERCHANT_CATEGORY VARCHAR,

    MERCHANT_CITY VARCHAR,
    MERCHANT_STATE VARCHAR,

    IS_ACTIVE BOOLEAN DEFAULT TRUE,

    CREATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    UPDATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_DIM_MERCHANT
        PRIMARY KEY (MERCHANT_KEY)
);