USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

SELECT

    COUNT(*) AS TOTAL_MERCHANTS,

    COUNT(DISTINCT MERCHANT_ID)
        AS DISTINCT_MERCHANTS,

    COUNT_IF(MERCHANT_ID IS NULL)
        AS NULL_MERCHANT_IDS,

    COUNT_IF(MERCHANT_NAME IS NULL)
        AS NULL_MERCHANT_NAMES,

    COUNT_IF(MERCHANT_CATEGORY IS NULL)
        AS NULL_MERCHANT_CATEGORIES

FROM DIM_MERCHANT;