USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS FACT_LOANS
(
    LOAN_KEY NUMBER IDENTITY(1,1),

    LOAN_ID VARCHAR NOT NULL,

    CUSTOMER_KEY NUMBER,
    CUSTOMER_ID VARCHAR,

    ACCOUNT_KEY NUMBER,
    ACCOUNT_ID VARCHAR,

    BRANCH_KEY NUMBER,
    BRANCH_ID VARCHAR,

    DATE_KEY NUMBER,

    LOAN_TYPE VARCHAR,
    LOAN_STATUS VARCHAR,

    ORIGINAL_PRINCIPAL NUMBER(18,2),

    OUTSTANDING_BALANCE NUMBER(18,2),

    INTEREST_RATE NUMBER(10,6),

    TERM_MONTHS NUMBER,

    MONTHLY_PAYMENT NUMBER(18,2),

    CURRENCY_CODE VARCHAR,

    ORIGINATION_DATE DATE,

    MATURITY_DATE DATE,

    SOURCE_FILE VARCHAR,

    RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ,

    CREATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_LOANS
        PRIMARY KEY (LOAN_KEY)
);
