USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

SELECT

COUNT(*) TOTAL_LOANS,

COUNT(DISTINCT LOAN_ID) DISTINCT_LOANS,

COUNT_IF(CUSTOMER_KEY IS NULL) NULL_CUSTOMER,

COUNT_IF(ACCOUNT_KEY IS NULL) NULL_ACCOUNT,

COUNT_IF(BRANCH_KEY IS NULL) NULL_BRANCH,

COUNT_IF(DATE_KEY IS NULL) NULL_DATE

FROM FACT_LOANS;

