USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

CREATE TABLE IF NOT EXISTS FACT_CREDIT_CARDS
(
    CARD_KEY NUMBER IDENTITY(1,1),

    CARD_ID VARCHAR NOT NULL,

    CUSTOMER_KEY NUMBER,
    CUSTOMER_ID VARCHAR,

    ACCOUNT_KEY NUMBER,
    ACCOUNT_ID VARCHAR,

    BRANCH_KEY NUMBER,
    BRANCH_ID VARCHAR,

    DATE_KEY NUMBER,

    CARD_PRODUCT VARCHAR,

    CARD_STATUS VARCHAR,

    CREDIT_LIMIT NUMBER(18,2),

    CURRENT_BALANCE NUMBER(18,2),

    AVAILABLE_CREDIT NUMBER(18,2),

    APR NUMBER(10,6),

    ISSUED_DATE DATE,

    EXPIRATION_DATE DATE,

    CURRENCY_CODE VARCHAR,

    SOURCE_FILE VARCHAR,

    RAW_LOAD_TIMESTAMP TIMESTAMP_NTZ,

    CREATED_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_FACT_CREDIT_CARDS
        PRIMARY KEY (CARD_KEY)
);