USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

SELECT

    COUNT(*) AS TOTAL_CARDS,

    COUNT(DISTINCT CARD_ID) AS DISTINCT_CARDS,

    COUNT_IF(CUSTOMER_KEY IS NULL) AS NULL_CUSTOMER,

    COUNT_IF(ACCOUNT_KEY IS NULL) AS NULL_ACCOUNT,

    COUNT_IF(BRANCH_KEY IS NULL) AS NULL_BRANCH,

    COUNT_IF(DATE_KEY IS NULL) AS NULL_DATE,

    COUNT_IF(CREDIT_LIMIT < 0) AS NEGATIVE_LIMIT,

    COUNT_IF(CURRENT_BALANCE < 0) AS NEGATIVE_BALANCE

FROM CORE.FACT_CREDIT_CARDS;