USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA CORE;

SELECT

    COUNT(*)                                   AS TOTAL_FRAUD,

    COUNT_IF(CUSTOMER_KEY IS NULL)             AS NULL_CUSTOMER_KEY,

    COUNT_IF(ACCOUNT_KEY IS NULL)              AS NULL_ACCOUNT_KEY,

    COUNT_IF(BRANCH_KEY IS NULL)               AS NULL_BRANCH_KEY,

    COUNT_IF(DATE_KEY IS NULL)                 AS NULL_DATE_KEY,

    COUNT_IF(MERCHANT_KEY IS NULL)             AS NULL_MERCHANT_KEY

FROM FACT_FRAUD;