/*****************************************************************************************
 Script Name : 13_create_grants.sql
******************************************************************************************/

USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE BANKING_ANALYTICS_DB TO ROLE DATA_ENGINEER;

GRANT USAGE ON ALL SCHEMAS IN DATABASE BANKING_ANALYTICS_DB
TO ROLE DATA_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN DATABASE BANKING_ANALYTICS_DB
TO ROLE DATA_ENGINEER;

GRANT USAGE ON WAREHOUSE WH_TRANSFORM
TO ROLE DATA_ENGINEER;

GRANT USAGE ON WAREHOUSE WH_ANALYTICS
TO ROLE DATA_ANALYST;

GRANT SELECT ON FUTURE TABLES
IN DATABASE BANKING_ANALYTICS_DB
TO ROLE READ_ONLY;