USE ROLE SYSADMIN;

USE DATABASE ENTERPRISE_BANKING;

USE SCHEMA RAW;


CREATE OR REPLACE TABLE RAW_BRANCHES (
    RAW_RECORD VARIANT,
    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
        DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE RAW_EMPLOYEES (
    RAW_RECORD VARIANT,
    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
        DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE RAW_CUSTOMERS (
    RAW_RECORD VARIANT,
    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
        DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE RAW_ACCOUNTS (
    RAW_RECORD VARIANT,
    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
        DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE RAW_LOANS (
    RAW_RECORD VARIANT,
    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
        DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE RAW_CREDIT_CARDS (
    RAW_RECORD VARIANT,
    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
        DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE RAW_TRANSACTIONS (
    RAW_RECORD VARIANT,
    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
        DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE RAW_FRAUD (
    RAW_RECORD VARIANT,
    SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER,
    LOAD_TIMESTAMP TIMESTAMP_LTZ
        DEFAULT CURRENT_TIMESTAMP()
);