USE ROLE SYSADMIN;

USE DATABASE ENTERPRISE_BANKING;

USE SCHEMA RAW;


CREATE OR REPLACE PIPE PIPE_BRANCHES
AUTO_INGEST = TRUE
AS
COPY INTO RAW_BRANCHES (
    RAW_RECORD,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @BANKING_RAW_STAGE/branches/
);


CREATE OR REPLACE PIPE PIPE_EMPLOYEES
AUTO_INGEST = TRUE
AS
COPY INTO RAW_EMPLOYEES (
    RAW_RECORD,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @BANKING_RAW_STAGE/employees/
);


CREATE OR REPLACE PIPE PIPE_CUSTOMERS
AUTO_INGEST = TRUE
AS
COPY INTO RAW_CUSTOMERS (
    RAW_RECORD,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @BANKING_RAW_STAGE/customers/
);


CREATE OR REPLACE PIPE PIPE_ACCOUNTS
AUTO_INGEST = TRUE
AS
COPY INTO RAW_ACCOUNTS (
    RAW_RECORD,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @BANKING_RAW_STAGE/accounts/
);


CREATE OR REPLACE PIPE PIPE_LOANS
AUTO_INGEST = TRUE
AS
COPY INTO RAW_LOANS (
    RAW_RECORD,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @BANKING_RAW_STAGE/loans/
);


CREATE OR REPLACE PIPE PIPE_CREDIT_CARDS
AUTO_INGEST = TRUE
AS
COPY INTO RAW_CREDIT_CARDS (
    RAW_RECORD,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @BANKING_RAW_STAGE/credit_cards/
);


CREATE OR REPLACE PIPE PIPE_TRANSACTIONS
AUTO_INGEST = TRUE
AS
COPY INTO RAW_TRANSACTIONS (
    RAW_RECORD,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @BANKING_RAW_STAGE/transactions/
);


CREATE OR REPLACE PIPE PIPE_FRAUD
AUTO_INGEST = TRUE
AS
COPY INTO RAW_FRAUD (
    RAW_RECORD,
    SOURCE_FILE,
    SOURCE_ROW_NUMBER
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        METADATA$FILE_ROW_NUMBER
    FROM @BANKING_RAW_STAGE/fraud/
);

ALTER PIPE PIPE_BRANCHES REFRESH;

SELECT SYSTEM$PIPE_STATUS('PIPE_BRANCHES');

ALTER PIPE PIPE_EMPLOYEES REFRESH;
ALTER PIPE PIPE_CUSTOMERS REFRESH;
ALTER PIPE PIPE_ACCOUNTS REFRESH;
ALTER PIPE PIPE_LOANS REFRESH;
ALTER PIPE PIPE_CREDIT_CARDS REFRESH;
ALTER PIPE PIPE_TRANSACTIONS REFRESH;
ALTER PIPE PIPE_FRAUD REFRESH;