USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE MART_CUSTOMER_360
(
    CUSTOMER_KEY NUMBER,

    CUSTOMER_ID VARCHAR,

    FULL_NAME VARCHAR,

    EMAIL VARCHAR,

    PHONE_NUMBER VARCHAR,

    CITY VARCHAR,

    STATE VARCHAR,

    CUSTOMER_PROFILE VARCHAR,

    CUSTOMER_STATUS VARCHAR,

    TOTAL_TRANSACTIONS NUMBER,

    TOTAL_DEPOSITS NUMBER(18,2),

    TOTAL_WITHDRAWALS NUMBER(18,2),

    TOTAL_LOANS NUMBER,

    OUTSTANDING_LOAN_BALANCE NUMBER(18,2),

    TOTAL_CREDIT_CARDS NUMBER,

    TOTAL_CREDIT_LIMIT NUMBER(18,2),

    CREDIT_BALANCE NUMBER(18,2),

    AVAILABLE_CREDIT NUMBER(18,2),

    FRAUD_CASES NUMBER,

    MAX_RISK_SCORE NUMBER,

    LAST_TRANSACTION_DATE TIMESTAMP_NTZ,

    REFRESH_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP()
);