USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE MART_BRANCH_PERFORMANCE
(
    BRANCH_KEY NUMBER,

    BRANCH_ID VARCHAR,

    BRANCH_CODE VARCHAR,

    BRANCH_NAME VARCHAR,

    BRANCH_TYPE VARCHAR,

    CITY VARCHAR,

    STATE VARCHAR,

    TOTAL_CUSTOMERS NUMBER,

    TOTAL_ACCOUNTS NUMBER,

    TOTAL_TRANSACTIONS NUMBER,

    TOTAL_DEPOSITS NUMBER(18,2),

    TOTAL_WITHDRAWALS NUMBER(18,2),

    TOTAL_LOANS NUMBER,

    TOTAL_LOAN_BALANCE NUMBER(18,2),

    TOTAL_CREDIT_LIMIT NUMBER(18,2),

    CURRENT_CREDIT_BALANCE NUMBER(18,2),

    FRAUD_CASES NUMBER,

    AVG_TRANSACTION_AMOUNT NUMBER(18,2),

    LAST_TRANSACTION_DATE TIMESTAMP_NTZ,

    REFRESH_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP()
);