USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA GOLD;

TRUNCATE TABLE MART_BRANCH_PERFORMANCE;

INSERT INTO MART_BRANCH_PERFORMANCE
(
    BRANCH_KEY,
    BRANCH_ID,
    BRANCH_CODE,
    BRANCH_NAME,
    BRANCH_TYPE,
    CITY,
    STATE,
    TOTAL_CUSTOMERS,
    TOTAL_ACCOUNTS,
    TOTAL_TRANSACTIONS,
    TOTAL_DEPOSITS,
    TOTAL_WITHDRAWALS,
    TOTAL_LOANS,
    TOTAL_LOAN_BALANCE,
    TOTAL_CREDIT_LIMIT,
    CURRENT_CREDIT_BALANCE,
    FRAUD_CASES,
    AVG_TRANSACTION_AMOUNT,
    LAST_TRANSACTION_DATE
)

WITH

TRANSACTION_SUMMARY AS
(
    SELECT
        BRANCH_KEY,
        COUNT(*) AS TOTAL_TRANSACTIONS,
        SUM(CASE WHEN TRANSACTION_DIRECTION='CREDIT'
                 THEN TRANSACTION_AMOUNT ELSE 0 END) TOTAL_DEPOSITS,
        SUM(CASE WHEN TRANSACTION_DIRECTION='DEBIT'
                 THEN TRANSACTION_AMOUNT ELSE 0 END) TOTAL_WITHDRAWALS,
        AVG(TRANSACTION_AMOUNT) AVG_TRANSACTION_AMOUNT,
        MAX(TRANSACTION_TIMESTAMP) LAST_TRANSACTION_DATE
    FROM CORE.FACT_TRANSACTIONS
    GROUP BY BRANCH_KEY
),

ACCOUNT_SUMMARY AS
(
    SELECT
        BRANCH_ID,
        COUNT(*) TOTAL_ACCOUNTS
    FROM CORE.DIM_ACCOUNT
    WHERE IS_CURRENT=TRUE
    GROUP BY BRANCH_ID
),

CUSTOMER_SUMMARY AS
(
    SELECT
        BRANCH_KEY,
        COUNT(DISTINCT CUSTOMER_KEY) TOTAL_CUSTOMERS
    FROM CORE.FACT_TRANSACTIONS
    GROUP BY BRANCH_KEY
),

LOAN_SUMMARY AS
(
    SELECT
        BRANCH_KEY,
        COUNT(*) TOTAL_LOANS,
        SUM(OUTSTANDING_BALANCE) TOTAL_LOAN_BALANCE
    FROM CORE.FACT_LOANS
    GROUP BY BRANCH_KEY
),

CARD_SUMMARY AS
(
    SELECT
        BRANCH_KEY,
        SUM(CREDIT_LIMIT) TOTAL_CREDIT_LIMIT,
        SUM(CURRENT_BALANCE) CURRENT_CREDIT_BALANCE
    FROM CORE.FACT_CREDIT_CARDS
    GROUP BY BRANCH_KEY
),

FRAUD_SUMMARY AS
(
    SELECT
        BRANCH_KEY,
        COUNT(*) FRAUD_CASES
    FROM CORE.FACT_FRAUD
    GROUP BY BRANCH_KEY
)

SELECT

    B.BRANCH_KEY,
    B.BRANCH_ID,
    B.BRANCH_CODE,
    B.BRANCH_NAME,
    B.BRANCH_TYPE,
    B.CITY,
    B.STATE,

    COALESCE(CS.TOTAL_CUSTOMERS,0),
    COALESCE(A.TOTAL_ACCOUNTS,0),
    COALESCE(T.TOTAL_TRANSACTIONS,0),
    COALESCE(T.TOTAL_DEPOSITS,0),
    COALESCE(T.TOTAL_WITHDRAWALS,0),
    COALESCE(L.TOTAL_LOANS,0),
    COALESCE(L.TOTAL_LOAN_BALANCE,0),
    COALESCE(CC.TOTAL_CREDIT_LIMIT,0),
    COALESCE(CC.CURRENT_CREDIT_BALANCE,0),
    COALESCE(F.FRAUD_CASES,0),
    COALESCE(T.AVG_TRANSACTION_AMOUNT,0),
    T.LAST_TRANSACTION_DATE

FROM CORE.DIM_BRANCH B

LEFT JOIN ACCOUNT_SUMMARY A
       ON B.BRANCH_ID = A.BRANCH_ID

LEFT JOIN TRANSACTION_SUMMARY T
       ON B.BRANCH_KEY = T.BRANCH_KEY

LEFT JOIN CUSTOMER_SUMMARY CS
       ON B.BRANCH_KEY = CS.BRANCH_KEY

LEFT JOIN LOAN_SUMMARY L
       ON B.BRANCH_KEY = L.BRANCH_KEY

LEFT JOIN CARD_SUMMARY CC
       ON B.BRANCH_KEY = CC.BRANCH_KEY

LEFT JOIN FRAUD_SUMMARY F
       ON B.BRANCH_KEY = F.BRANCH_KEY;