USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE MART_FRAUD_ANALYTICS
(
    FRAUD_CASE_ID VARCHAR,

    TRANSACTION_ID VARCHAR,

    CUSTOMER_KEY NUMBER,
    CUSTOMER_ID VARCHAR,

    ACCOUNT_KEY NUMBER,
    ACCOUNT_ID VARCHAR,

    BRANCH_KEY NUMBER,
    BRANCH_ID VARCHAR,

    DATE_KEY NUMBER,

    MERCHANT_KEY NUMBER,

    MERCHANT_NAME VARCHAR,
    MERCHANT_CATEGORY VARCHAR,

    TRANSACTION_TYPE VARCHAR,
    TRANSACTION_CHANNEL VARCHAR,

    TRANSACTION_AMOUNT NUMBER(18,2),

    FRAUD_TYPE VARCHAR,
    RISK_SCORE NUMBER,
    RISK_LEVEL VARCHAR,
    CASE_STATUS VARCHAR,

    DETECTED_DATE DATE,
    DETECTED_TIMESTAMP TIMESTAMP_NTZ,

    BRANCH_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,

    REFRESH_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP()
);