USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA GOLD;

TRUNCATE TABLE MART_FRAUD_ANALYTICS;

INSERT INTO MART_FRAUD_ANALYTICS
(
    FRAUD_CASE_ID,
    TRANSACTION_ID,
    CUSTOMER_KEY,
    CUSTOMER_ID,
    ACCOUNT_KEY,
    ACCOUNT_ID,
    BRANCH_KEY,
    BRANCH_ID,
    DATE_KEY,
    MERCHANT_KEY,
    MERCHANT_NAME,
    MERCHANT_CATEGORY,
    TRANSACTION_TYPE,
    TRANSACTION_CHANNEL,
    TRANSACTION_AMOUNT,
    FRAUD_TYPE,
    RISK_SCORE,
    RISK_LEVEL,
    CASE_STATUS,
    DETECTED_DATE,
    DETECTED_TIMESTAMP,
    BRANCH_NAME,
    CITY,
    STATE
)

SELECT

    F.FRAUD_CASE_ID,

    F.TRANSACTION_ID,

    T.CUSTOMER_KEY,
    F.CUSTOMER_ID,

    T.ACCOUNT_KEY,
    F.ACCOUNT_ID,

    T.BRANCH_KEY,
    F.BRANCH_ID,

    T.DATE_KEY,

    COALESCE(T.MERCHANT_KEY,2180929),

    COALESCE(M.MERCHANT_NAME,'UNKNOWN'),

    COALESCE(M.MERCHANT_CATEGORY,'UNKNOWN'),

    F.TRANSACTION_TYPE,

    F.TRANSACTION_CHANNEL,

    F.TRANSACTION_AMOUNT,

    F.FRAUD_TYPE,

    F.RISK_SCORE,

    F.RISK_LEVEL,

    F.CASE_STATUS,

    F.DETECTED_DATE,

    F.DETECTED_TIMESTAMP,

    B.BRANCH_NAME,

    B.CITY,

    B.STATE

FROM CORE.FACT_FRAUD F

LEFT JOIN CORE.FACT_TRANSACTIONS T
       ON F.TRANSACTION_ID = T.TRANSACTION_ID

LEFT JOIN CORE.DIM_BRANCH B
       ON T.BRANCH_KEY = B.BRANCH_KEY

LEFT JOIN CORE.DIM_MERCHANT M
       ON T.MERCHANT_KEY = M.MERCHANT_KEY;