USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE MART_EXECUTIVE_KPI
(
    SNAPSHOT_DATE DATE,

    TOTAL_CUSTOMERS NUMBER,

    ACTIVE_CUSTOMERS NUMBER,

    TOTAL_ACCOUNTS NUMBER,

    ACTIVE_ACCOUNTS NUMBER,

    TOTAL_BRANCHES NUMBER,

    TOTAL_TRANSACTIONS NUMBER,

    TOTAL_DEPOSITS NUMBER(18,2),

    TOTAL_WITHDRAWALS NUMBER(18,2),

    NET_TRANSACTION_AMOUNT NUMBER(18,2),

    AVERAGE_TRANSACTION_AMOUNT NUMBER(18,2),

    TOTAL_LOANS NUMBER,

    OUTSTANDING_LOAN_BALANCE NUMBER(18,2),

    TOTAL_CARDS NUMBER,

    TOTAL_CREDIT_LIMIT NUMBER(18,2),

    TOTAL_CARD_BALANCE NUMBER(18,2),

    TOTAL_AVAILABLE_CREDIT NUMBER(18,2),

    CREDIT_UTILIZATION_PCT NUMBER(8,2),

    TOTAL_FRAUD_CASES NUMBER,

    FRAUD_RATE_PCT NUMBER(8,4),

    REFRESH_TIMESTAMP TIMESTAMP_NTZ
        DEFAULT CURRENT_TIMESTAMP()
);