USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA GOLD;

TRUNCATE TABLE MART_EXECUTIVE_KPI;

INSERT INTO MART_EXECUTIVE_KPI
(
    SNAPSHOT_DATE,
    TOTAL_CUSTOMERS,
    ACTIVE_CUSTOMERS,
    TOTAL_ACCOUNTS,
    ACTIVE_ACCOUNTS,
    TOTAL_BRANCHES,
    TOTAL_TRANSACTIONS,
    TOTAL_DEPOSITS,
    TOTAL_WITHDRAWALS,
    NET_TRANSACTION_AMOUNT,
    AVERAGE_TRANSACTION_AMOUNT,
    TOTAL_LOANS,
    OUTSTANDING_LOAN_BALANCE,
    TOTAL_CARDS,
    TOTAL_CREDIT_LIMIT,
    TOTAL_CARD_BALANCE,
    TOTAL_AVAILABLE_CREDIT,
    CREDIT_UTILIZATION_PCT,
    TOTAL_FRAUD_CASES,
    FRAUD_RATE_PCT
)

WITH

CUSTOMER_STATS AS
(
    SELECT
        COUNT(*) TOTAL_CUSTOMERS,
        COUNT_IF(IS_CURRENT) ACTIVE_CUSTOMERS
    FROM CORE.DIM_CUSTOMER
),

ACCOUNT_STATS AS
(
    SELECT
        COUNT(*) TOTAL_ACCOUNTS,
        COUNT_IF(IS_CURRENT) ACTIVE_ACCOUNTS
    FROM CORE.DIM_ACCOUNT
),

BRANCH_STATS AS
(
    SELECT
        COUNT(*) TOTAL_BRANCHES
    FROM CORE.DIM_BRANCH
),

TRANSACTION_STATS AS
(
    SELECT

        COUNT(*) TOTAL_TRANSACTIONS,

        SUM(
            CASE
                WHEN TRANSACTION_DIRECTION='CREDIT'
                THEN TRANSACTION_AMOUNT
                ELSE 0
            END
        ) TOTAL_DEPOSITS,

        SUM(
            CASE
                WHEN TRANSACTION_DIRECTION='DEBIT'
                THEN TRANSACTION_AMOUNT
                ELSE 0
            END
        ) TOTAL_WITHDRAWALS,

        AVG(TRANSACTION_AMOUNT)
            AVERAGE_TRANSACTION_AMOUNT

    FROM CORE.FACT_TRANSACTIONS
),

LOAN_STATS AS
(
    SELECT

        COUNT(*) TOTAL_LOANS,

        SUM(OUTSTANDING_BALANCE)
            OUTSTANDING_LOAN_BALANCE

    FROM CORE.FACT_LOANS
),

CARD_STATS AS
(
    SELECT

        COUNT(*) TOTAL_CARDS,

        SUM(CREDIT_LIMIT)
            TOTAL_CREDIT_LIMIT,

        SUM(CURRENT_BALANCE)
            TOTAL_CARD_BALANCE,

        SUM(AVAILABLE_CREDIT)
            TOTAL_AVAILABLE_CREDIT

    FROM CORE.FACT_CREDIT_CARDS
),

FRAUD_STATS AS
(
    SELECT
        COUNT(*) TOTAL_FRAUD_CASES
    FROM CORE.FACT_FRAUD
)

SELECT

    CURRENT_DATE(),

    C.TOTAL_CUSTOMERS,

    C.ACTIVE_CUSTOMERS,

    A.TOTAL_ACCOUNTS,

    A.ACTIVE_ACCOUNTS,

    B.TOTAL_BRANCHES,

    T.TOTAL_TRANSACTIONS,

    COALESCE(T.TOTAL_DEPOSITS,0),

    COALESCE(T.TOTAL_WITHDRAWALS,0),

    COALESCE(T.TOTAL_DEPOSITS,0)
        -
    COALESCE(T.TOTAL_WITHDRAWALS,0),

    COALESCE(T.AVERAGE_TRANSACTION_AMOUNT,0),

    L.TOTAL_LOANS,

    COALESCE(L.OUTSTANDING_LOAN_BALANCE,0),

    CC.TOTAL_CARDS,

    COALESCE(CC.TOTAL_CREDIT_LIMIT,0),

    COALESCE(CC.TOTAL_CARD_BALANCE,0),

    COALESCE(CC.TOTAL_AVAILABLE_CREDIT,0),

    CASE
        WHEN CC.TOTAL_CREDIT_LIMIT=0 THEN 0
        ELSE ROUND(
            (CC.TOTAL_CARD_BALANCE/
             CC.TOTAL_CREDIT_LIMIT)*100,2)
    END,

    F.TOTAL_FRAUD_CASES,

    CASE
        WHEN T.TOTAL_TRANSACTIONS=0 THEN 0
        ELSE ROUND(
            (F.TOTAL_FRAUD_CASES/
             T.TOTAL_TRANSACTIONS)*100,4)
    END

FROM CUSTOMER_STATS C
CROSS JOIN ACCOUNT_STATS A
CROSS JOIN BRANCH_STATS B
CROSS JOIN TRANSACTION_STATS T
CROSS JOIN LOAN_STATS L
CROSS JOIN CARD_STATS CC
CROSS JOIN FRAUD_STATS F;