USE DATABASE ENTERPRISE_BANKING;
USE SCHEMA GOLD;

SELECT 'MART_CUSTOMER_360' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM MART_CUSTOMER_360

UNION ALL

SELECT 'MART_BRANCH_PERFORMANCE', COUNT(*)
FROM MART_BRANCH_PERFORMANCE

UNION ALL

SELECT 'MART_FRAUD_ANALYTICS', COUNT(*)
FROM MART_FRAUD_ANALYTICS

UNION ALL

SELECT 'MART_EXECUTIVE_KPI', COUNT(*)
FROM MART_EXECUTIVE_KPI;

--------------------------------------------------------------
-- Business Validation Queries
---------------------------------------------------------------

-- Customer counts
SELECT COUNT(*) FROM CORE.DIM_CUSTOMER WHERE IS_CURRENT=TRUE;
SELECT COUNT(*) FROM GOLD.MART_CUSTOMER_360;

-- Branch counts
SELECT COUNT(*) FROM CORE.DIM_BRANCH;
SELECT COUNT(*) FROM GOLD.MART_BRANCH_PERFORMANCE;

-- Fraud counts
SELECT COUNT(*) FROM CORE.FACT_FRAUD;
SELECT COUNT(*) FROM GOLD.MART_FRAUD_ANALYTICS;

-- Executive KPI should always contain one snapshot
SELECT COUNT(*) FROM GOLD.MART_EXECUTIVE_KPI;